#!/usr/bin/env bash

echo "Starting build"

add_lunch_combo fox_BG6-eng

export FOX_AB_DEVICE=1
export TW_DEFAULT_LANGUAGE="en"
export ALLOW_MISSING_DEPENDENCIES=true
export LC_ALL="C"
export OF_MAINTAINER="Kyros70"
export FOX_BUILD_TYPE="Unofficial"
export FOX_MAINTAINER_PATCH_VERSION="1"
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export FOX_USE_NANO_EDITOR=1
export OF_HIDE_NOTCH=1
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_STATUS_H=80
export OF_STATUS_INDENT_LEFT=65
export OF_STATUS_INDENT_RIGHT=50
export FOX_ENABLE_APP_MANAGER=1
export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_ZSTD_BINARY=1
export OF_USE_LZ4_COMPRESSION=1
export OF_FLASHLIGHT_ENABLE=0
export FOX_NO_SAMSUNG_SPECIAL=1
export OF_FORCE_PREBUILT_KERNEL=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_NO_REFLASH_CURRENT_ORANGEFOX=1
export FOX_VENDOR_BOOT_RECOVERY=1
export OF_USE_GREEN_LED=0
export OF_ENABLE_LPTOOLS=1
export OF_USE_LEGACY_BATTERY_SERVICES=1
